chore: download/install rtorrent packages only if they are not already installed

diff --git a/src/software/official/rtorrent/rtorrent b/src/software/official/rtorrent/rtorrent
--- a/src/software/official/rtorrent/rtorrent
+++ b/src/software/official/rtorrent/rtorrent
@@ -16,8 +16,14 @@
 # @note Disables SC2154 because the variable is defined in the main script.
 # shellcheck disable=SC2154
 zen::software::rtorrent::add() {
-    if [[ ! -d "/srv/rutorrent" ]]; then
-        rtorrent_binaries=("xmlrpc-c" "libtorrent-rakshasa" "rtorrent")
+    rtorrent_binaries=("xmlrpc-c" "libtorrent-rakshasa" "rtorrent")
+    not_installed=()
+    for pkg in "${rtorrent_binaries[@]}"; do
+        if ! dpkg -s "$pkg" >/dev/null 2>&1; then
+            not_installed+=("$pkg")
+        fi
+    done
+    if [[ ${#not_installed[@]} -gt 0 ]]; then
         zen::validate::input "version" "$software_version"
         valid_versions=$(zen::software::get_config_key_value "$software_config_file" '.arguments.versions[]')
         valid_version_found=false
@@ -27,10 +33,12 @@ zen::software::rtorrent::add() {
                 break
             fi
         done
-        [[ ! "$valid_version_found" ]] && mflibs::status::error "$(zen::i18n::translate "errors.software.invalid_version" "$app_name" "$software_version")"
-        zen::git::download_folder "/tmp" "MediaEase/binaries" "main" "dist/current"
+        if [[ "$valid_version_found" == false ]]; then
+            mflibs::status::error "$(zen::i18n::translate "errors.software.invalid_version" "$app_name" "$software_version")"
+        fi
+        zen::git::download_folder "/tmp" "MediaEase/binaries" "main" "dist/current/$app_name/$software_version"
+        deb_files=$(ls "/tmp/binaries/dist/current/$app_name/$software_version"/*.deb)
         for binary in "${rtorrent_binaries[@]}"; do
-            deb_files=(/tmp/binaries/dist/current/*.deb)
             if [[ "$binary" == "xmlrpc-c" ]]; then
                 xmlrpc_latest_version=$(find /tmp/binaries/dist/current -name "xmlrpc-c*.deb" -print0 | xargs -0 ls -1 | sort -V | tail -n 1)
                 mflibs::shell::text::yellow "$(zen::i18n::translate "messages.dependency.unpack_deb_file" "$xmlrpc_latest_version")"
@@ -53,13 +61,15 @@ zen::software::rtorrent::add() {
                 fi
             done
         done
+        # Configure the app. This will also generate the proxy file
+        zen::software::rtorrent::config
+        # Generate the service file, this will also start it
+        zen::service::generate "$app_name" "false" "true"
+        # Create a backup file
+        zen::software::backup::create "$app_name" "$software_config_file"
+    else
+        mflibs::status::warn "$(zen::i18n::translate "messages.software.already_installed" "$app_name")"
     fi
-    # configure the app. This will  also generate the proxy file
-    zen::software::rtorrent::config
-    # generate the service file, this will also start it
-    zen::service::generate "$app_name" "false" "true"
-    # create a backup file
-    zen::software::backup::create "$app_name" "$software_config_file"
 }
 
 ################################################################################
