fix: pnpm installation process

diff --git a/src/dependencies.yaml b/src/dependencies.yaml
--- a/src/dependencies.yaml
+++ b/src/dependencies.yaml
@@ -37,19 +37,20 @@ mediaease:
           chown -R $CADDYFILE_OWNER /etc/caddy
     - pnpm:
         install: |
-          wget -qO- https://get.pnpm.io/install.sh | sh >/dev/null 2>&1
           PNPM_PATH="/root/.local/share/pnpm"
           PNPM_BIN="/usr/local/bin"
-          if [ -f "${PNPM_PATH}/pnpm" ]; then
-            for binary in pnpm pnpx; do
-              if [ -f "${PNPM_BIN}/${binary}" ]; then
-                rm -f "${PNPM_BIN}/${binary}" || echo "Failed to remove ${PNPM_BIN}/${binary}"
-              fi
-              cp -pR "${PNPM_PATH}/${binary}" "${PNPM_BIN}/${binary}" || echo "Failed to copy ${PNPM_PATH}/${binary} to ${PNPM_BIN}/${binary}"
-              chmod +x "${PNPM_BIN}/${binary}" || echo "Failed to set executable permissions for ${PNPM_BIN}/${binary}"
-            done
+          wget -qO- https://get.pnpm.io/install.sh | sh >/dev/null 2>&1
+          if [ -d "${PNPM_PATH}" ]; then
+            if [ -d "${PNPM_BIN}/pnpm" ]; then
+              rm -rf "${PNPM_BIN}/pnpm" || echo "Failed to remove ${PNPM_BIN}/pnpm"
+            fi
+            if [ -f "${PNPM_BIN}/pnpx" ]; then
+              rm -f "${PNPM_BIN}/pnpx" || echo "Failed to remove ${PNPM_BIN}/pnpx"
+            fi
+            chmod -R +x "${PNPM_PATH}" || echo "Failed to set executable permissions for files in ${PNPM_PATH}"
+            cp -r "${PNPM_PATH}"/* "${PNPM_BIN}/" || echo "Failed to copy files from ${PNPM_PATH} to ${PNPM_BIN}"
           else
-            echo "PNPM not found at ${PNPM_PATH}/pnpm"
+            echo "PNPM not found at ${PNPM_PATH}"
           fi
 airsonic:
   apt: oracle-java17-installer openjdk-17-jre oracle-java17-set-default ffmpeg
